"""Forensic report writer (design doc step 11): every THINK line, tool call,
observation, gate decision and the final verdict, rendered as Markdown so the case
file is readable without this software — plus machine-readable `run.json` next to it.

The report deliberately records what was *not* observed too (skipped tools, absent
API keys, non-TTY kill-switch), because an investigation report that hides its own
blind spots is worthless as evidence.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

HEADER = """# SENTINEL-IR — forensic investigation report

| field | value |
|---|---|
| case id | `{case_id}` |
| evidence file | `{eml}` |
| SHA-256 (recorded before analysis) | `{sha}` |
| size | {size} bytes |
| started (UTC) | {started} |
| finished (UTC) | {finished} |
| reasoning brain | `{brain}`{brain_note} |
| safety | tool whitelist · hard timeout {timeout}s · sandbox `{sandbox}` · kill-switch `{kill}` · human gate `{gate}` |
| chain-of-custody | {custody} |
| evidence ledger | `{chain_ref}` |

> Generated by a local agent. Everything between the `<EMAIL_DATA>` markers in the
> raw file is attacker-controlled text and was treated as evidence, never as
> instructions. Locations are investigative leads (approximate), not identity proof.
"""


def render(case: dict[str, Any], events: list[dict[str, Any]], results: list[dict[str, Any]],
           verdict: dict[str, Any], chain: dict[str, Any]) -> str:
    lines: list[str] = [HEADER.format(
        case_id=case["case_id"], eml=case["eml"], sha=case["sha256"], size=case["size"],
        started=case["started"], finished=case["finished"], brain=case["brain"],
        brain_note=case.get("brain_note", ""), timeout=case["timeout_s"],
        sandbox=case["sandbox"], kill=case["kill"], gate=case["gate"],
        custody=case["custody"], chain_ref=chain.get("file", "n/a"),
    )]

    lines.append("\n## 1 · Verdict\n")
    lines.append(f"**{verdict['verdict']}** — confidence **{verdict['confidence']:.1f}%**, "
                 f"ensemble risk score **{verdict['risk']:.1f}/100**.\n")
    lines.append(verdict.get("summary", "").strip() + "\n")

    lines.append("\n### Evidence used to reach this verdict\n")
    for b in verdict.get("evidence", []):
        lines.append(f"- {b}")
    gaps = verdict.get("gaps") or []
    if gaps:
        lines.append("\n### What was NOT observed (do not read as clean)\n")
        for g in gaps:
            lines.append(f"- {g}")

    lines.append("\n### Origin & geolocation (honesty panel)\n")
    lines.append("```text\n" + "\n".join(verdict.get("origin_lines") or ["(no origin data)"]) + "\n```\n")

    lines.append("\n## 2 · Risk score evolution\n\n| step | tool | status | Δ score | running | note |\n|---|---|---|---|---|---|\n")
    for r in results:
        lines.append(f"| {r.get('n', '')} | `{r.get('tool', '')}` | {r.get('status', '')} | {r.get('delta', '')} | "
                     f"{r.get('risk_after', '')} | {(r.get('summary') or '')[:110].replace('|', '/')} |")

    lines.append("\n## 3 · Tool observations (full structured output)\n")
    for r in results:
        lines.append(f"\n### 3.{r.get('n')} `{r.get('tool')}` — {r.get('status')} ({r.get('ms', '?')} ms)\n")
        if r.get("error"):
            lines.append(f"**error:** `{r['error']}`\n")
        data = r.get("data") or {}
        if data:
            blob = json.dumps(data, indent=2, default=str, sort_keys=True)
            if len(blob) > 26_000:
                blob = blob[:26_000] + "\n… (truncated; full data in run.json)"
            lines.append("```json\n" + blob + "\n```\n")
        for sig in r.get("signals", []):
            lines.append(f"- signal `{sig.get('factor')}` dir={sig.get('direction')} strength={sig.get('strength')} — {sig.get('explanation')}")

    lines.append("\n## 4 · Agent transcript (THINK → CHOOSE TOOL → ACT → OBSERVE)\n")
    for ev in events:
        kind = ev.get("kind")
        if kind == "thought":
            lines.append(f"\n**think** · {ev.get('text', '')}\n")
        elif kind == "gate":
            lines.append(f"\n**[{ev.get('tag', 'CONFIRM_NEEDED')}]** · {ev.get('text', '')} → **{ev.get('decision', '')}**\n")
        elif kind == "refusal":
            lines.append(f"\n**refused** · {ev.get('text', '')}\n")
        elif kind == "meta":
            lines.append(f"\n_harness · {ev.get('text', '')}_\n")

    if chain.get("blocks"):
        lines.append("\n## 5 · Blockchain evidence log\n")
        lines.append("```json\n" + json.dumps(chain, indent=2, default=str, sort_keys=True) + "\n```\n")
        if chain.get("ganache"):
            lines.append(f"\nOn-chain: tx `{chain['ganache'].get('tx_hash', 'n/a')}` "
                         f"(contract `{chain['ganache'].get('contract', 'n/a')}`, "
                         f"status `{chain['ganache'].get('ok')}`)\n")

    lines.append("\n## 6 · Safety parameter attestation\n")
    for item in case.get("safety_lines", []):
        lines.append(f"- {item}")
    lines.append("\n---\n_Report generated locally by SENTINEL-IR. No cloud inference was used; "
                 "no raw evidence was placed on-chain — hashes and verdict metadata only._\n")
    return "\n".join(lines)


def write(case_dir: Path, *, case: dict[str, Any], events: list[dict[str, Any]], results: list[dict[str, Any]],
          verdict: dict[str, Any], chain: dict[str, Any],
          signals: Optional[list[dict[str, Any]]] = None) -> tuple[Path, Path]:
    md = render(case, events, results, verdict, chain)
    report = case_dir / "report.md"
    report.write_text(md, encoding="utf-8")
    machine = case_dir / "run.json"
    machine.write_text(json.dumps({"case": case, "events": events, "results": results,
                                   "verdict": verdict, "chain": chain,
                                   # the full risk ledger, not just the bullets that survived the
                                   # summary cut — a reviewer must be able to recompute the score
                                   "signals": signals or [],
                                   "written_utc": datetime.now(timezone.utc).isoformat(timespec="seconds")},
                                  indent=2, default=str, sort_keys=True), encoding="utf-8")
    for p in (report, machine):
        try:
            p.chmod(0o600)   # case files may contain sensitive evidence references
        except OSError:
            pass
    return report, machine
